import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/layout/frontend/partials/header";
import Footer from "@/components/layout/frontend/partials/footer";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "User Panel",
  description: "Generated by create next app",
};

export default async function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeType = cookieStore.get("theme")?.value.toString() || 'light';
  const theme = themeType === 'light' ? 'bg-white' : 'bg-gray-700';
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={theme}>
          <Header themeValue={themeType} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
